# Generated by Django 5.2 on 2025-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='percentage',
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
    ]
