# Generated by Django 5.2 on 2025-07-01 08:21

from django.db import migrations, models
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_score_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time_taken',
            field=models.DurationField(default=timedelta(seconds=0)),
            preserve_default=False,
        ),
    ]
